# Generated by Django 4.1.4 on 2022-12-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='Egypt', max_length=150, null=True),
        ),
    ]
