# Generated by Django 4.1.4 on 2022-12-27 12:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hear', models.CharField(max_length=200)),
                ('hear_brand', models.TextField()),
                ('see_brand', models.TextField()),
                ('speaking_brand', models.TextField()),
                ('buy_before', models.CharField(max_length=200)),
                ('use_before', models.CharField(max_length=200)),
                ('rating_experience', models.IntegerField()),
                ('rating_feedback', models.IntegerField()),
                ('sharing_probabilite', models.IntegerField()),
                ('other_brand', models.CharField(max_length=200)),
                ('best_brand', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('sent_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
