# Generated by Django 4.1.4 on 2022-12-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_hear',
        ),
    ]
