# Generated by Django 4.1.4 on 2022-12-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_survey_is_hear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='best_brand',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='buy_before',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='hear_brand',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='other_brand',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='rating_experience',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='rating_feedback',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='see_brand',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='sharing_probabilite',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='speaking_brand',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='use_before',
        ),
    ]
