# Generated by Django 4.1.4 on 2022-12-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_survey_best_brand_remove_survey_buy_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='user_age',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='survey',
            name='user_country',
            field=models.CharField(blank=True, default='egypt', max_length=150, null=True),
        ),
    ]
