# Generated by Django 4.1.4 on 2023-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_surveyno'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyno',
            name='products',
            field=models.TextField(default='null'),
        ),
    ]
